# Generated by Django 5.1.4 on 2025-01-04 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(3000)]),
        ),
    ]
