# Generated by Django 5.1.4 on 2025-01-04 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_alter_employee_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='employees_count',
        ),
    ]
